# Spring properties
spring:
  application:
     name: ws-recommendation-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://ws-registration-service/eureka/

